version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file: "./.env"
    image: "/backend-img"
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "frontend-img"
    ports:
      - "3000:3000"
    links:
      - "backend"
